### ISSUE TITLE
Random mix disappeared 

### ISSUE THREAD

**Issue by webby1972** [LMS-Community/slimserver#1137]
Random mix (Logitech plugin) disappeared after update. Still in the plugin list but not active.

![Screenshot 2024-07-21 at 19-05-46 Lyrion Music Server](https://github.com/user-attachments/assets/c4ab8320-cee1-4081-b4e0-ed7850a5e565)

![Screenshot 2024-07-21 at 19-07-42 Lyrion Music Server](https://github.com/user-attachments/assets/2f35ae78-eb7d-4984-8d0d-6b78ebb00efe)

Logitech Media Server Versie: 8.5.2 - 1716215514 @ Tue 21 May 2024 04:21:20

(https://wiki.slimdevices.com/index.php/Random_Mix.html)

**Comment by mikehd1959** [comment]
Same here. The shortcut on my Music Sources homepage results in an empty track list. Random Releases is working.
Version: 8.5.3 - 1721022124 @ Tue Jul 16 04:11:12 WEDT 2024

**Comment by CDrummond** [comment]
This is because you are using Material skin and this has moved 'Random Mix' to the "..." menu in the Queue view. The reason for this is that the 'Random Mix' does not cause a browsing of you music, hence is different to all other entries under 'My Music', and allows starting, and stopping, of mixes. Navigating to 'My Music / Random Mix' (IMVHO) did not make sense, hence moving to the Queue view (which is what 'Random Mix' affects/controls). Also, with LMS9.0, Material will show a dice icon (in the queue and now-playing views) when 'Random Mix' is active, allowing you to stop the mix from a (again, IMVHO) more logical place.

@mherger I think this issue should be closed, as its not an LMS issue.

**Comment by CDrummond** [comment]
@mikehd1959 Again, this is a Material skin issue. From 5.1.1 any _existing_ links will work.

**Comment by CDrummond** [comment]
This 'Random Mix' change has been reverted in Material, as will be as before when 5.1.1 is released.

**Comment by webby1972** [comment]
Thank you!

**Comment by mikehd1959** [comment]
Yes, thank you.

**Comment by michaelherger** [comment]
Thanks @CDrummond for chiming in!

**Comment by theking2** [comment]
difficult to find compared to the big button but here it is:

<img width="1012" height="442" alt="Image" src="https://github.com/user-attachments/assets/09e7c9f5-3d96-44ce-9afc-4628c6df48b0" />

**Comment by CDrummond** [comment]
@theking2 That is the _status_ icon (it shows when random mix is active - and also allows stopping of random mix). Not sure what you mean by "the big button" - but if you mean the "Random Mix" entry in "My Music", then that's still there.
