### ISSUE TITLE
sha1 needs to be upgraded

### ISSUE THREAD

**Issue by viviparous** [LMS-Community/slimserver#117]
sha1 is deprecated

**Comment by maniacgit** [comment]
As a first step exchanging Digest::SHA1 by Digest::SHA works, I've already changed this locally and no issues so far.

On nearly all places it should be possible to switch sha1 to sha512 also, I'm only unsure about the Slim/Utils/Firmware.pm, since there sha1 is used to match a checksum with a downloaded file.

**Comment by mherger** [comment]
More places which need more work:
* plugin repositories: 3rd parties would need to update their plugins and repository files
* mysb.com interaction: needs mysb side changes, too

**Comment by mherger** [comment]
MySB interaction issue has been resolved in LMS 8.2 by using a new auth system.
