### ISSUE TITLE
Default to HTTPS for www.mysqueezebox.com?

### ISSUE THREAD

**Issue by mavit** [LMS-Community/slimserver#170]
I see that `www.mysqueezebox.com` supports HTTPS, but Logitech Media Server uses plain HTTP, for, e.g., imageproxy requests, only attempting HTTPS when sending a password.  Is there any reason not to use HTTPS all the time?

### Background
Following the hints at http://wiki.slimdevices.com/index.php/Connecting_remotely#HTTPS.2FSSL_Tunnelling, I’m looking at putting LMS behind an HTTPS proxy.  One of the niggles I’ve encountered is that my browser then refuses to load artwork images over HTTP.  I’ve worked around this by enabling the `useLocalImageproxy` setting in LMS, but it did cause me to wonder if it would be better nowadays to simply default to HTTPS wherever possible.

**Comment by mherger** [comment]
Hehe... your comment in the forum made think about this earlier today. IIRC the reason for the lack of global use of https is that we hit some issues where secured connections would fail for some installations. I therefore had to add some fallback code. But I lacked the time to implement this fallback/failure tolerance into all of the existing calls. It's definitely something to consider.

Please keep in mind that players and some other clients would still not support SSL (and won't ever). In order to prevent them using un-secured http you'd have to use the LMS local image proxy. (You could actually use your own external resizing proxy, but that's little tested so far...)

**Comment by mavit** [comment]
Automatic fall-back is nice for users, but it could be bad for security; you think you’ve got HTTPS, but as soon as something goes wrong you silently end up with HTTP.  Are the problematic installations cases where people are running on a cut-down operating system on NAS device or similar and lack the required libraries?  Perhaps the simplest thing would be to make this a configuration option that people with troublesome installations could switch off?  I'm happy to have a go at creating a pull request if that seems like a worthwhile approach.

**Comment by michaelherger** [comment]
Fixed in commit fffb61f8ae8fffc03623598cad9bcd0acb519abb
