### ISSUE TITLE
iTunes Album Artwork broken on MacOS Sierra

### ISSUE THREAD

**Issue by jcferguson** [LMS-Community/slimserver#178]
I'm running 7.91 - 1509357021 on MacOS 10.12.6, connecting to five RPi 3 devices all running PiCorePlayer v3.22. Three are connected via Ethernet and two via wireless. iTunes version is 12.7.1.14.

Since upgrading to 7.9.1 (from 7.7) much of the album art is missing (>50%). It doesn't seem to matter whether the artwork was obtained from the Apple store using the iTunes interface or placed into the tags from another source e.g. Amazon. 

I've done a clean reinstall a couple of times, the same albums are missing the album art after each reinstall. I've been unable to find any consistency in why some are missing and some aren't. Reinstalling the artwork in iTunes may or may not work. Extract iTunes Artwork is checked in server settings. The server is always on so should be able to update even if it takes a long time. 

This is the third of three problems I'm experiencing with 7.91.

**Comment by mherger** [comment]
Can you run a full wipe & rescan with logging set to to debug for the scanner (see the dropdown at the top of Settings/Advanced/Logging). Then provide the scanner.log file (there's a link to download the zipped file in Settings/Information).

**Comment by jcferguson** [comment]
Scanner log attached.
[scanner.log.zip](https://github.com/Logitech/slimserver/files/1476915/scanner.log.zip)

On spot-checking two albums that don't show artwork and two that do show album artwork in LMS, I found the following anomalies (or maybe not).
If any of the music files are viewed in Finder, the artwork is displayed. 
In iTunes, all files show the artwork in both album info view and song info view for all songs, even if viewed individually. 
Viewing the same albums in two different third party ID3 tag editor, albums that do not show artwork in LMS either have no artwork associated with the songs or show only one or two songs with artwork. And albums that are showing artwork in LMS also show the artwork in the Artwork tag for every song on the album. 

After running the requested scanner log and attaching it, I tried updating one of the albums that had some songs with missing artwork in the ID3 Artwork tag and ran a "Look for new and changed media files" scan. On completion, that album now shows artwork in LMS.

There appears that the artwork is stored in the file in two different places or under two different tag names. Still exploring this.  

This is looking like not an LMS problem but an iTunes problem in how artwork is stored in the song file.

**Comment by mherger** [comment]
Quite a log file... and little spectacular to be found. A few quick things:
* remove the Album Artwork folder from the folders to scan: LMS would not be able to make the link between artwork found in there and your music
* disable scanning for images: this has nothing to do with album artwork, but would allow you to scan folders with your images to be presented on some DLNA renderer
* disable the MusicIP plugin - you don't seem to be running MusicIP

But as you've figured out yourself the main issue is that the artwork stored by iTunes does not show up. This feature never left the "beta" status, means it never worked reliably. Unfortunately it seems things have gotten even worse:

```[17-11-15 15:44:58.3646] Slim::Plugin::iTunes::Importer::Artwork::OSX::exportSingleArtwork (107) Error: Error from artwork script: Usage: itartwork.scpt PATH [--all | --iter INDEX | --single SEARCH_STRING TRACK_ID | --shutdown ] [ --skip-unchecked ]```

All over the place. It seems the script is broken. 

While you could wait for this to be fixed, it's unlikely going to happen anytime soon. Considering the fact it never reliably worked I fear the situation hasn't improved much.

I'd therefore rather suggest you embed the artwork using a tool relying on tags rather than its internal database to store the images. Unfortunately I wouldn't even know what tool to use on Mac. I myself am using Media Rage - a product which has not seen an update in several years... and the company's domain name is up for sale. Nothing to recommend. mp3tag is the tool of choice for many on Windows.

**Comment by bsweeney** [comment]
FYI I've used a script hosted by dougscripts in the past with success for this task:
https://dougscripts.com/itunes/scripts/ss.php?sp=embedart

It appears there's an updated version as well written as an applet, but I have not tried that one:
https://dougscripts.com/itunes/scripts/ss.php?sp=reembedartwork
