### ISSUE TITLE
Using the jsonrpc.js interface from a web browser

### ISSUE THREAD

**Issue by paul-1** [LMS-Community/slimserver#201]
I'm using simple javascript to make calls to the jsonrpc interface from a different machine than is running the LMS server.   The browser is complaining because "Access-Control-Allow-Origin" is not set in the Response header.  The funny thing is that the data is actual sent from the server, but since the Origin is not allowed, the data is web browser blocks the content from being passed to the javascript client.

This change resolves the problem.  This is only an issue for a web browser.....other methods do not appear to care about this header value (wget, curl.....etc)  

```
diff --git a/Slim/Web/JSONRPC.pm b/Slim/Web/JSONRPC.pm
index 66e7850..683ee6a 100644
--- a/Slim/Web/JSONRPC.pm
+++ b/Slim/Web/JSONRPC.pm
@@ -265,6 +265,7 @@ sub writeResponse {
        
        # set a content type to 1.1 proposed value. Should work with 1.0 as it is not specified
        $httpResponse->content_type('application/json');
+       $httpResponse->header('Access-Control-Allow-Origin' => '*' );
        
        use bytes;
```
Is there an issue with setting this header value?

**Comment by mherger** [comment]
NOT a good idea :-). What you experience is a security feature. If we enabled access from anywhere as you suggest, LMS would be vulnerable to all kinds of attacks. Eg. http://i-m-the-bad-guy.org could install its nasty plugin on your LMS if you happened to visit that page. 

What exactly are you trying to do? Are you trying to get information from LMS to be shown in the pCP web UI? You could either achieve this by having pCP's web server do the request for you, or by implementing a plugin in LMS which would give selective access to LMS using JSONP. Or extend LMS to properly support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by paul-1** [comment]
Yes, I'm trying to build a simple control app in the pCP interface.  Nothing different than any of the remote control apps do today (They don't need to install plugins)

I understand a full CORS implementation on LMS would be the better choice, but I don't understand how this "bandaid" opens LMS up to anything that it already is not open to.  This is only setting a response header, this is a web-browser only client issue.   LMS still does everything that I ask it to.   It still processes the request and sends the data back to the client......the browser client is just preventing the data from being used.

**Comment by mherger** [comment]
Are you running your code from an http source or local file? This should not be possible. And I'm almost certain it wasn't in the past, as one of my plugins tried to do this, and I had to implement a JSONP handler in my plugin.

**Comment by paul-1** [comment]
My LMS server is a dedicated box.   The code is running in javascript which is is a page of the the pCP web interface.   I'll send you a note with the code.

**Comment by michaelherger** [comment]
Ok, here's my suggestion: LMS does come with a basic CSRF protection pref (Settings/Advanced/Security). This is on by default. If a user decides to turn it off, we can allow the request. Otherwise we block it (before executing the command).

**Comment by mherger** [comment]
This should be fixed in commit c6733dd. Just make sure you don't enable CSRF in LMS.

**Comment by decibyte** [comment]
I'm aware this would involve more work than the current fix, but wouldn't it be better to add a new security option for setting a value for the "Access-Control-Allow-Origin" response header and the include this header if the options is set? I think compromising CSRF for this is a bad idea (and I believe you already know that).

Would that be a very complex or somewhat trivial task? I'm asking because I wish I could propose an actual fix, but I know nothing about Perl (yet) and wonder whether this could be an easy "getting started" task.

**Comment by mherger** [comment]
@decibyte - thanks for your offer to help!

But actually, no, I didn't think mixing this in with the CSRF setting was bad. Why should I? I think both approaches do serve the same purpose. And rather than confuse the user even more (the CSRF description in LMS is awful!), I'd prefer to keep things simple. If the user doesn't care about commands/page requests being sent to LMS then oh well... (the fact that this is the default is kind of troubling, though).

You should easily be able to add a new pref to Slim/Web/Settings/Server/Security.pm (IIRC). There's prefs call which would return the list of prefs to be handled. Just add yours. Then check the path for the page template. Edit it to handle that pref. That's for setting it. Now go into S/W/JSONRPC.pm where I set that header, and use $prefs->get('yourpref') || 'defaultvalue' instead of the asterisk. Makes sense?

**Comment by decibyte** [comment]
> Makes sense?

Sort of. I'll see if I can find the time to give it a try some day :)

Thx!
