### ISSUE TITLE
enable correct strict checking on ssl setting

### ISSUE THREAD

**Issue by sanderant** [LMS-Community/slimserver#208]
Per:
https://forums.slimdevices.com/showthread.php?109059-7-9-2-RPM-with-SSL-errors

I'll take your word that you know what this means. :)

**Comment by michaelherger** [comment]
For the record: here's the _warning_ mentioned in that thread:

> [18-05-18 09:47:50.0838] Slim::Utils::Misc::msg (1252) Warning: [09:47:50.0835] 
> ************************************************** *****************
> Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
> is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
> possibly with SSL_ca_file|SSL_ca_path for verification.
> If you really don't want to verify the certificate and keep the
> connection open to Man-In-The-Middle attacks please set
> SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
> ************************************************** *****************
> at /usr/share/perl5/vendor_perl/Slim/Networking/Async/HTTP.pm line 98.
> [18-05-18 09:47:50.2077] Slim::Utils::Misc::msg (1252) Warning: [09:47:50.2075] ************************************************** *****************
> Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
> is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
> possibly with SSL_ca_file|SSL_ca_path for verification.
> If you really don't want to verify the certificate and keep the
> connection open to Man-In-The-Middle attacks please set
> SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.

As I said: this is a _warning_. And it's not caused by LMS itself, but likely by the rather old Perl version CentOS is using (5.16). It defaults to _not_ verifying SSL certs. And the newer OpenSSL implementation warns about this. We are supposed to set `SSL_verify_mode` explicitly, rather than rely on the default. But our code does rely on defaults in a first step, falling back to `SSL_verify_mode=SSL_VERIFY_NONE ` if needed. 

See https://github.com/Logitech/slimserver/blob/cb4085808d35eb09ff067e1c1a9a0e9a75fe4551/Slim/Networking/Async/HTTP.pm#L87

**Comment by mherger** [comment]
@sanderant - could you please give the latest nightly another try?
