### ISSUE TITLE
Special characters (Umlaute) in path names

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#328]
I know it may not be best practice, _but_: If there are Umlaute in path names, they are displayed correctly in one place and scrambled in another:

- [Path (Hörspiele) shown correctly in "Basic Settings" tab](https://ibb.co/j4621Yn)
- [Path shown scrambled in "Scan Progress"](https://ibb.co/9yc426f)

**Comment by michaelherger** [comment]
Do you see the same in the Default Skin?

**Comment by schnillerman** [comment]
Puh - gute Frage. Ich stelle mal kurz um.

Am Di., 28. Apr. 2020 um 13:29 Uhr schrieb michaelherger <
notifications@github.com>:

**Comment by schnillerman** [comment]
> Do you see the same in the Default Skin?

In short: [Yes.](https://ibb.co/4Vj8fX0)

Longer: ... trifft sowohl fürs Nightly der 7.9.2 als auch fürs Nightly der 8.x Version zu.

Danke für die schnelle Antwort!

**Comment by schnillerman** [comment]
... trifft sowohl fürs Nightly der 7.9.2 als auch fürs Nightly der 8.x Version zu.

**Comment by michaelherger** [comment]
Ist das ein Netzwerk-Share? Welches Betriebsystem läuft auf dem Rechner? Über welches Protokoll ist das Laufwerk angebunden? Welches OS läuft auf dem Server/NAS?

**Comment by michaelherger** [comment]
Ah, und noch was: ist das "nur" ein kosmetisches Problem, oder treten beim Einlesen Probleme auf?

**Comment by schnillerman** [comment]
Das ist ein Netzwerk-Share auf einer Synology DiskStation (Linux-basiert), eingebunden auf dem LMS Server (bunsenlabs Linux, Debian-Derivat) per CIFS.

**Das ganze scheint nur ein kosmetisches Problem zu sein, da alles soweit funktioniert.**

**Comment by Moonbase59** [comment]
Same here, on Ubuntu Studio 14.04.6, using local ext4-formatted disc and ~150,000 music files on LMS 7.9.2 - 1578996832. Purely cosmetic (logs, scan progress), otherwise these play fine and tags are shown correctly on all devices. I use very long and foreign file names (English, German, Danish, Russian, Chinese, Japanese). These are all encoded as UTF-8 (as is my system locale).

Only problem here: My two "main" folders to scan are
```bash
~/Musik/Tagged
~/Musik/Schräg
```
and the `Schräg` folder seems not to be scanned anymore (not even when trying to do it manually). You can select it from the file/folder view, then `Schräg` immediately turns to `SchrÃ¤g`. I cannot make out why, but it mostly doesn’t get scanned (very few times, every few months, it seems to do it).

The only other (very minor) problem is when using http[s] links into my system (for Home Assistant alerts, mainly): LMS’ "direct URL" and Home Assistant’s URIs seem to use URLEncode which of course don’t map correctly to UTF-8 file names via GET or the like.

**Comment by mherger** [comment]
@Moonbase59 so you're saying this issue isn't purely cosmetic, but scans actually fail if a path has an umlaut in it?

**Comment by mw9** [comment]
The display issue looks to have been addressed in LMS 8.3 via PR #678, _Fix scan progress reporting - 'raw' path names need to be decoded_.

**Comment by mherger** [comment]
Thanks! I'll consider this fixed.
