### ISSUE TITLE
OGF format 

### ISSUE THREAD

**Issue by philippe44** [LMS-Community/slimserver#343]
When using OggFlac on a stream, the actual ContentType comes from the parsed HTTP headers that the server responds to the GET request. What I've seen is that RP (and others) set application/ogg and not application/ogf. 

As a result, LMS sets ContentType to ogg and checks against that in Slim::Player::SqueezeBox2.pm, #648 $client->contentTypeSupported(). It caused me some pain as I had "ogg" disabled as an accepted codec (ogg = vorbis/opus in LMS terminology) and I only had "ogf". So the streaming was failing because LMS thought that "ogg" was not in supported format and it took me a while to realize that as my attention was on OggFlac decoding.

It's not a big deal b/c so far the only client that support ogf is squeezelite and usually supports ogg as well, but in case user disable ogg, then we have an inconsistency.

Shouldn't we change Slim::Player::Protocol::HTTP.pm::parseHeaders where, when it's a recognized ogf (isOgf == true) but the HTTP header says 'ogg' to overwrite ContentType to 'ogf'?

**Comment by Moonbase59** [comment]
What is "RP"?

Shouldn’t OggFLAC be covered by `audio/ogg`, with a possible `codecs=flac` parameter?
I always found the use of the `application` top-level type a bit problematic for media content anyway, and also `application/ogg` has been redefined in [RFC 5334](https://www.xiph.org/ogg/doc/rfc5334.txt).

Is "ogf" a LMS invention? I never heard of `application/ogf` or `audio/ogf` MIME types before, and couldn’t find it on the [IANA page](https://www.iana.org/assignments/media-types/media-types.xhtml).

If in need, since the `codecs=` parameter is optional, I’d probably try to read the file’s first header page to find the codec used since it’s mandatory to have it there with Ogg files.

Surely not representative, but I just pulled a quick one and served up the _one (!)_ Ogg FLAC file I have in my test set via Home Assistant’s Python web server. Here is the header returned:
```
HTTP/1.0 200 OK =>
Cache-Control => public, max-age=2678400
Content-Type => audio/ogg
Last-Modified => Wed, 04 Sep 2019 13:02:38 GMT
Content-Length => 35354760
Accept-Ranges => bytes
Date => Sun, 24 May 2020 09:17:52 GMT
Server => Python/3.7 aiohttp/3.6.1
```
`file` and `mimetype` return `audio/x-flac+ogg` (maybe my system is too old though):
```bash
$ file 01\ -\ Blind\ Faith.oga
01 - Blind Faith.oga: Ogg data, FLAC audio
$ mimetype 01\ -\ Blind\ Faith.oga 
01 - Blind Faith.oga: audio/x-flac+ogg
```

For those interested (from xiph.org):
[Specification of MIME types and respective codecs parameter](https://wiki.xiph.org/index.php/MIMETypesCodecs)
[MIME Types and File Extensions](https://wiki.xiph.org/MIME_Types_and_File_Extensions)
[FLAC → Ogg Mapping](https://xiph.org/flac/ogg_mapping.html)
[Ogg logical and physical bitstream overview](https://xiph.org/vorbis/doc/oggstream.html)

**Comment by philippe44** [comment]
RP is RadioParadise :-)

Yes, I totally agree that it seems that mimetype audio/ogg should be audio/ogg;codecs=flac. This is what I use in my UPnP and Cast bridges and it seems to satisfy various players. It is also consistent with opus practices. 

The issue with LMS is a bit different as it sends its player a "stream" message describing what it (the player) is about to GET in term of codec format, and this is where "ogf" is a LMS "codec" invention. With that message, players receive an URL where to actually "GET" the audio. That URL can be local to LMS if the audio is proxied or if it is a local file, but it can also be a remote URL. 

LMS players list their codecs capacity to LMS when they connect, and ogg = ogg/vorbis, ops=ogg/vorbis and ogf=ogg/flac, this is where "ogf" comes from.

For remote formats, LMS is not able to identify the codec format when it sends the "stream" message then it tells the player to start buffering and wait till he (LMS) figures out the format and sends a further message that will allow player's decoder to start. That further message will contain the "ogf" format as well when if it is oggflac and "ops" when it is oggopus. 

So the player is not involved in figuring out the actual format by analysing mimetypes, it's all LMS jobs, AFAIK. When the payer GETs the URL, it does not care about what's in it *except* when there is ICY metadata, in which case it can feedback LMS with metadata update when it arrives.

To be back to my post, RP sends a header with "application/ogg" as a mimetype so LMS has to open the actual stream, get the first bytes, figure out what it really is (vorbis, opus, flac) then close the stream (unless it is proxied) and tell the player "hey, here is where to find the audio and here is what it is".

So the inconsistency I was pointed is that when checking if the player can support the streamed audio, LMS uses the HTTP header's mimetypes (application/ogg in case of RP) not the actual format found by streaming a few 100's bytes. Therefor, if the player has told it supports "ogf" but not "ogg", playback will fail. In practice, this is not a big deal as squeezelite today always supports ogg and maybe ogf, but it still can be a probem as users can decide the actual list of supported codec.

**Comment by Moonbase59** [comment]
Thanks for taking the time to explain all this in depth. I always love to know the inner workings better, appreciate it! And RP is a great find, too.

Without knowing much of the inner technicalities, I’d support anything that helps LMS stay at top quality without compromising its wide compatibility. After all, we bought all that beautiful Slimdevices and Logitech stuff for a reason. And we love the openness and ongoing support and new possibilities with software players like SqueezeLite.

So yes, I’d be in favour of your suggestion.

**Comment by mherger** [comment]
Isn't this what PR #351 addressed?

**Comment by philippe44** [comment]
Yes, so I’ll close it
