### ISSUE TITLE
Tidal is not streaming on SBT

### ISSUE THREAD

**Issue by tomcat24** [LMS-Community/slimserver#451]
Squeezebox touch is not able to stream Tidal. I had a similar issue (#438) few weeks back and it was diagnosed as a problem with Tidal switching from HTTP to HTTPS.

**Comment by mherger** [comment]
Yes, they enabled https streaming again. Would you be able to update to the latest LMS 8 nightly?

BTW: are you US or EU based?

**Comment by mherger** [comment]
Related to #438

**Comment by tomcat24** [comment]
you want me to upgrade to LMS 8?
Based in the US.

**Comment by mherger** [comment]
Yes, the changes on their end required quite important changes to LMS. I plan to "officially" release LMS8 pretty soon anyway.

**Comment by tomcat24** [comment]
Doing it right now, Thanks!

**Comment by m7hofer** [comment]
same issue here but using LMS 8.0.0 (with daphile) already
location: EU

Logitech Media Server Version: 8.0.0 - git99457a8 @ Daphile 20.08-x86_64
Server HTTP Port Number: 9000
Operating system: Linux - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.30.3 - x86_64-linux-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.066
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

on DAC which connected to daphile server most titles can't be played because stream fails to open, e.g.

[20-11-10 14:09:53.7323] Slim::Player::Song::open (490) Warning: stream failed to open [wimp://51799903.flac].
[20-11-10 14:09:54.0605] Slim::Player::Song::open (490) Warning: stream failed to open [wimp://83175844.flac].

**Comment by michaelherger** [comment]
@m7hofer please ping Kimmo of Daphile. He's always lagging a bit behind, as he has to pick up our changes and build it in to his. I've sent him a mail earlier today, but haven't heard back yet.

**Comment by zsuffad** [comment]
I had the same error on 7.9 and after upgrading to the 8 nightly: logitechmediaserver_8.0.0~1604995301_arm.deb Tidal playback is working again. (On a raspberry pi 3).
THX.

**Comment by m7hofer** [comment]
@mherger thanks a lot for the quick help. You're doing an incredible job.
