### ISSUE TITLE
Logitec Media Server does not run on fresh Debian buster

### ISSUE THREAD

**Issue by jniggemann** [LMS-Community/slimserver#500]
Freshly installed Debian 10 System (i386) with perl 5.28.1.
Installing either `logitechmediaserver_8.1.0_all.deb`  or `logitechmediaserver_8.1.0_i386.de`  went without warnings or error messages, yet in both cases, the server dies every 5 seconds because of missing perl modules (DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name).

Installing the corresponding debian packages for the modules and linking to them from /usr/share/squeezebox/CPAN resolves this, but then lms complains about module version incompatibilities.

Question 1: Why are the above-mentioned modules missing from the deb package? I'm sure I'm missing something obvious here.
Question 2: It's Jan 1st and although I'm not too hungover, I was unable to find information on how to install manually from the tarball.

I'm spoiled by some 20 years of Debian use, expecting packages to declare dependencies that apt can eventually resolve, or be self-contained and bring everything they need.

**Comment by michaelherger** [comment]
> Question 1: Why are the above-mentioned modules missing from the deb package? I'm sure I'm missing something obvious here.

Unfortunately no, you're not missing the obvious. Many years ago we decided to include dependencies, rather than relying on the system. This was to prevent conflicts we were facing. Unfortunately this means we have to build binaries for every platform. As this accumulates a lot of files and work I tend to only build for popular platforms. i386 is no longer on that list...

> Question 2: It's Jan 1st and although I'm not too hungover, I was unable to find information on how to install manually from the tarball.

That said, you're not alone... please see https://forums.slimdevices.com/showthread.php?113550-Old-computers-and-LMS&p=1001868&viewfull=1#post1001868 for community provided files. If they prove to be good we might include them in future builds.

**Comment by jniggemann** [comment]
> Unfortunately this means we have to build binaries for every platform. As this accumulates a lot of files and work I tend to only build for popular platforms. i386 is no longer on that list...
That's understandable, 386 is no longer common these days.

> That said, you're not alone... please see https://forums.slimdevices.com/showthread.php?113550-Old-computers-and-LMS&p=1001868&viewfull=1#post1001868 for community provided files. If they prove to be good we might include them in future builds.

Seems to work somewhat as I now get 
`DBI.c: loadable library and perl binaries are mismatched (got handshake key 0x80c0080, needed 0x8140080)`

Can you point me to the instructions for a manual installation from the tar file?

**Comment by michaelherger** [comment]
As you might have seen from that discussion, that tarball has its issues. You're probably better off compiling yourself (as outlined in the thread).
