### ISSUE TITLE
Useless module HTML::TreeBuilder

### ISSUE THREAD

**Issue by mavit** [LMS-Community/slimserver#594]
The module in `CPAN/HTML/TreeBuilder.pm` isn't used anywhere by LMS, and can't be being used by plugins because it depends on several other modules that we don't bundle.

Trying to `use` it results in `Can't locate HTML/Tagset.pm in @INC (you may need to install the HTML::Tagset module) (@INC contains: ...`.

**Comment by michaelherger** [comment]
I think we added it years ago to support some plugins. Might have been mine only...

Does this cause a problem for you?

**Comment by mavit** [comment]
No problem.  It’s just that I tried to use `HTML::Element` (which is part of the same CPAN distribution as `HTML::TreeBuilder`), and was surprised that it wasn’t present.

**Comment by PaulWebster** [comment]
Just as FYI ... this came up today because I recently starting using HTML::Treebuilder in my RadioNowPlaying plugin and a user reported that the plugin would not load .... seemingly because Perl could not find Treebuilder. So is it missing from a CPAN configuration script for users who have their own CPAN set-up?
https://forums.slimdevices.com/showthread.php?115201-Announce-Radio-Now-Playing-plugin&p=1035559&viewfull=1#post1035559
