### ISSUE TITLE
SqueezePlay.pm: Possible wrong string compare???

### ISSUE THREAD

**Issue by chincheta0815** [LMS-Community/slimserver#909]
Hej there,

I am trying to get some proper Mute Info into Squeezelite and found something possibly wrong in Slim/Player/SqueezePlay.pm.

Shouldn't the regexp in that line: https://github.com/Logitech/slimserver/blob/a063401fe91bc81889f3ca2524f1ce6ab349879c/Slim/Player/SqueezePlay.pm#L250

`...
if (abs($fade) > 1 || $client->model !~ /baby|fab4/) {
...`

rather be
`...
if (abs($fade) > 1 || $client->model =~ /baby|fab4/) {
...`

Otherwise the comment 
`# for long fades do standard behavior so that sleep/alarm work`
 does not make any sense (at least) to me: squeezelite usually has no internal alarm function.

The issue would also explain why I am getting fade on mute and unmute with squeezelite...

**Comment by chincheta0815** [comment]
I created a pull request: https://github.com/Logitech/slimserver/pull/910

**Comment by michaelherger** [comment]
You try to revert/modify a change @philippe44 applied three years ago specifically (I would assume) for squeezelite(-esp). See https://github.com/Logitech/slimserver/commit/12100ea9bcda9e163ce39b9c2b7ffe7bc9ae21e3.

What is the exact issue you're trying to solve? Fading in/out IMHO is expected behavior.
