### ISSUE TITLE
Bug: problem with player synchronization (only AudioAddict di.fm, jazzradio.com)

### ISSUE THREAD

**Issue by knovash** [LMS-Community/slimserver#993]
There is a problem with player synchronization. When the radio AudioAddict (di.fm, jazzradio.com) is playing. (Premium account) its playing ok when unsynced.
the players are connecting. but the music is not playing.
there is no problem with other radios (somafm) and spotify.
I tried it on all versions 8.4.x
sometimes after that, the server freezes and needs to be restarted
the server was running on orangepi arabian or a mint laptop.
for many years before version 8.4, everything worked fine
https://www.youtube.com/watch?v=2ObvIeC3hr4

**Comment by mherger** [comment]
Thanks for reporting. Would there be anything in your server.log (see Settings/Information)?

**Comment by CornelisJ** [comment]
I suppose that you need a premium account when playing these stations on Squeezebox players. With a free account for jazzradio.com, I get following errors in LMS server.log. I tried to play 2 of the today's 5 free channels. These 5 free channels do play in my web browser.

[24-02-13 10:33:56.2850] Slim::Utils::Scanner::Remote::__ANON__ (236) Error: Can't connect to remote server to retrieve playlist for, http://prem1.jazzradio.com/blues?5bf4ae68243b74d7cea07974: 401 Authentication Required.
[24-02-13 10:34:46.7970] Slim::Utils::Scanner::Remote::__ANON__ (236) Error: Can't connect to remote server to retrieve playlist for, http://prem1.jazzradio.com/bossanova?5bf4ae68243b74d7cea07974: 401 Authentication Required.

**Comment by mherger** [comment]
Yes, these are subscription based services. TBH: I don't remember whether there should be a free (poor quality) stream or something. Do you know?

**Comment by CornelisJ** [comment]
No, I don't know. I only know that with a free subscription you can listen to 5 free channels (that change daily) via their website.
It would be useful to know if **knovash** has a premium account for these services, and if has entered username and password of his premium account via LMS > Settings > Advanced > JAZZRADIO.com. FYI, I subscribed for a free account in an attempt to reproduce the issue. But I am not going to subscribe for a premium account.

**Comment by knovash** [comment]
> Thanks for reporting. Would there be anything in your server.log (see Settings/Information)?

I try to find errors in log bгt nothing.. tell me which logging settings to enable..

**Comment by michaelherger** [comment]
Try `plugin.audioaddict`.

**Comment by knovash** [comment]
https://www.youtube.com/watch?v=2ObvIeC3hr4
https://www.youtube.com/watch?v=VtC40uATDMI

**Comment by knovash** [comment]
has anyone caught the same bug?

**Comment by git828** [comment]
not exactly the same problem . Sync is working , but my channels (also a premium user) crash a lot of time (all 5-10 min) too since i changed to the local plugin. 
After rebooting Server, it runs for a few hours. 
I will try to run debug level of plugin audioaddict.


Edit:
Get a crash right now .
Log

[24-06-14 15:23:51.1186] Slim::Player::Protocols::HTTP::readMetaData (248) Metadata: StreamTitle='Inon Bramy - Angels';              
[24-06-14 15:24:20.9420] Slim::Player::Protocols::HTTP::readPersistentChunk (499) Persistent streaming from 155835314 up to 1718410767 for http://prem2.jazzradio.com/smoothvocals?a653d4049365b71a2430ae7e
[24-06-14 15:24:21.3476] Slim::Player::Protocols::HTTP::readMetaData (248) Metadata: QÈu¤Å\N¹
rYôK=t¹oeU³ÏÕÂôóFs©(rGl[Åµ·ÆÆf*ÍÛ½qð³@  º4^CAÈ4Þp¸©KËÉ¨!FôLÀBQF4#èÕWrýúB¦¡pR.¥,h»f¾@®*ÓdaR.2
 L¼àÂ¸ïq!ÿÿèZKýFIÀ÷Mò2kþùf»§ôÞaØDÅÔ]Lh*í"j®d~¯ÿ8l¦
m\ÍJ­sL¿ÿÿÿ¿gßÿáäNÿûâdþ*S{P«¹|v³¬¤m¯ºh-ëBÎañÂÌ³gY²¿@ B~9¼
`géF®
ÉcÕiZ2el
Ð©UÁ`°DAaÐp¹U(/è¡ÒJ-eÜH&jT¨R8·jªî»E)gIî²±êÁ©Ö[V´ÃLº&ºÝ`¦N«Js>D!R×¡²M®´Á[ZhfìÀÓIâ¢TÌ¤:ùT©íÃo{uk+½¸MÔÖw1$Í!òd£ù,bZú5ÒdÓGÊõ|«8C¨n ZXf
¢[ E¶¤üób\¸Ñ\^I4¼ç0rYwÀZ	·¦DÞ©Q¹d¸ Ø³ÈdÂNt#r!f7^¯4IØÑ_ÓpÚÛ·S;StreamTitle='DW3 - I Got You';  z WJR(|×ÓG±[Ryã>ðúÀ 
Ø¹9®YXpéÀ	¦Z÷&
\Êþjy[Zòïá5?¸KeýxÛøÅc4éL;zäæºùBùs÷·;töûðüÿÿþò
7«ÄÀ1Äâ,m
4ùc¥ý\ÞH­7UÍVad`TGBr­¦Â÷pFhôXác1 ¡OãÿÿH¯WNpí­mW¾él<
ÿßMîÛµ@r~bØe²¹ÍÆ
"øgç©(
0µµ ÀÄW¹À ¢Áf LºéÖÒåôp
À¬¬LJ -1qIZûCSâ§p )â÷­Â¼Ì)¸×tdVÎôçy3VËY£N$¼!ÙÂ¨
Ðá¹
ETgIuË{DÅÁ-²fv+Ð 9c¹Ìe,R*Õ©´¤Æ"¥Å,àM ý?N²fOô0eÚ¶.p¤
Èã*rá#
DPÍ ð¬âÌA¬3 
AÜ¾¾Ü¨fvª`9Ûª©Õ.E ¶¶¹¤N¦#mRíH\"\×ßg!ÏËJÓyÂõDÚdý7Q
ÑO´5MTÕF½øÄ

**Comment by knovash** [comment]
Logitech Media Server Version: 8.5.3 - 1718138983 @ Wed 12 Jun 2024 04:17:27 AM CEST
its work!!! bug fixed!
close issue?

**Comment by knovash** [comment]
> not exactly the same problem . Sync is working , but my channels (also a premium user) crash a lot of time (all 5-10 min) too since i changed to the local plugin. After rebooting Server, it runs for a few hours. I will try to run debug level of plugin audioaddict.
> 
> Edit: Get a crash right now . Log
> 
> [24-06-14 15:23:51.1186] Slim::Player::Protocols::HTTP::readMetaData (248) Metadata: StreamTitle='Inon Bramy - Angels'; [24-06-14 15:24:20.9420] Slim::Player::Protocols::HTTP::readPersistentChunk (499) Persistent streaming from 155835314 up to 1718410767 for http://prem2.jazzradio.com/smoothvocals?a653d4049365b71a2430ae7e [24-06-14 15:24:21.3476] Slim::Player::Protocols::HTTP::readMetaData (248) Metadata: QÈu�¤Å�\N�¹ rY�ôK=t¹oeU³�ÏÕÂôó�Fs©(rGl[�Åµ�·Æ��Æf_ÍÛ��½qð³��@ �� º�4^CAÈ4Þp¸©�K�ËÉ¨!TÕF½��ø�Ä

the same new trouble... but its di.fm bug not lms...
https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1713663-di-fm-plugin-bugs


DI.FM Support
Hi Konstantin, 
Thank you for your reply and the screenshots. 
Please note that Premium Icecast streaming is limited to 1 active connection at a time per our TOS (terms of service).
If you have multiple active connections, our system will block additional connections.
Let us know if you have any additional questions or feedback. 
Kind regards,

**Comment by knovash** [comment]
Logitech Media Server Version: 8.5.3 - 1718138983 @ Wed 12 Jun 2024 04:17:27 AM CEST
its work!!! bug fixed!
